/**
 * Turns the logo SVGs exported from Figma into path data the app can render
 * with react-native-svg, so the logo is always the designer's exact vectors.
 *
 * Re-run after replacing a file in assets/brand: npm run gen:brand
 */
import { readFileSync, writeFileSync } from 'node:fs';

const sources = {
  mark: 'assets/brand/agriova-mark.svg',
  wordmark: 'assets/brand/agriova-wordmark.svg',
};

const entries = Object.entries(sources).map(([name, file]) => {
  const svg = readFileSync(file, 'utf8');
  const viewBox = svg.match(/viewBox="([^"]+)"/)[1];
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  return `  ${name}: {\n    viewBox: '${viewBox}',\n    paths: [\n${paths
    .map((d) => `      '${d}',`)
    .join('\n')}\n    ],\n  },`;
});

const out = `// Generated by scripts/gen-brand.mjs from assets/brand. Do not edit by hand.
// prettier-ignore
export const brandPaths = {
${entries.join('\n')}
} as const;
`;

writeFileSync('src/ui/brandPaths.ts', out);
console.log('wrote src/ui/brandPaths.ts');
